# Site settings
title: hxer Blog
SEOTitle: hxer Blog
header-img: img/home-bg-keyboard.png
email: hxer7963@outlook.com
description: "筚路蓝缕, 以启山林."
keyword: "算法、系统、源码、论文、数学、人生、幸福"
url: "https://hxer.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
zhihu_username:     he-xin-10-66
github_username:    hxer7963



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
# Use sskatex math engine: https://kramdown.gettalong.org/math_engine/sskatex.html
# and KaTeX: https://github.com/Khan/KaTeX#rendering-options
markdown: kramdown
kramdown:
  math_engine: sskatex
  math_engine_opts:
    katex_js: 'katex/katex.min.js'
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# 评论系统: https://www.jianshu.com/p/2940e0eda89f
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: '4099bea87f4c3afdbb65'    #生成的clientID 不要用我的
  clientSecret: 'b94831ce0c37d255c1867bf80798e40b77ccd568'   #生成的clientSecret 不要用我的
  repo: blog_gitalk    #仓库(存放评论的项目)名称
  owner: hxer7963    #github用户名
  admin: hxer7963    #拥有admin权限的用户
  distractionFeeeMode: true  # 类似于Facebook阴影效果
  labels: ['Gitalk']  # 用于生产Issue的标签


# Disqus settings
disqus_username: false

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics
ba_track_id: 3a4e9c7228e29bbd4c40c77c2906a93b

# Google Analytics
ga_track_id: 'UA-127322971-1'            # Format: UA-xxxxxx-xx
ga_domain: hxer.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "For the next quantum leap<br>离开世界之前，总得留下点什么"
sidebar-avatar: /img/avatar-qiaoba.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# search plugin: https://github.com/androiddevelop/jekyll-search
search: false


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
